spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FREIGHT
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    show-sql: true