server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FREIGHT
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
