CREATE TABLE VEHICLE_DETAILS (
	VEHICLE_ID serial NOT NULL,
	VEHICLE_MODEL varchar(100) NOT NULL,
	VEHICLE_DOCUMENT varchar(60) NOT NULL,
	DRIVER_DOCUMENT varchar(60) NOT NULL,
	DRIVER_ANNOTATIONS varchar(255) NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	DAT_UPDATE TIMESTAMP NOT NULL,
	CUSTOMER_ID integer NOT NULL UNIQUE,
	CONSTRAINT VEHICLE_DETAILS_pk PRIMARY KEY (VEHICLE_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE REGISTRY (
	REGISTRY_ID serial NOT NULL,
	BATCH_ID integer NOT NULL,
	REGISTRY_DESCRIPTION varchar(255) NOT NULL,
	REGISTRY_REMAINING_TIME varchar(255) NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	CONSTRAINT REGISTRY_pk PRIMARY KEY (REGISTRY_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE BATCH (
	BATCH_ID serial NOT NULL,
	DRIVER_CUSTOMER_CODE varchar(36) NOT NULL,
	CUSTOMER_REQUESTER_ID integer NOT NULL,
	BATCH_CODE varchar(255) NOT NULL UNIQUE,
	BATCH_ESTIMATED_TIME varchar(255) NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	BATCH_DESCRIPTION TEXT,
	BATCH_WEIGHT FLOAT NOT NULL,
	BATCH_PRICE FLOAT NOT NULL,
	BATCH_MULTIPLIER FLOAT NOT NULL,
	BATCH_CONSTRAINT varchar(45) NOT NULL,
	BATCH_DESTINY_ADDRESS integer NOT NULL,
	BATCH_UNLOCK_CODE varchar(10) NOT NULL,
	CONSTRAINT BATCH_pk PRIMARY KEY (BATCH_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE ADDRESS (
	ADDRESS_ID serial NOT NULL,
	ADDRESS_STREET varchar(50) NOT NULL,
	ADDRESS_NUMBER integer NOT NULL,
	ADDRESS_BLOCK varchar(50) NOT NULL,
	ADDRESS_CODE varchar(10) NOT NULL,
	ADDRESS_CITY varchar(50) NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	DAT_UPDATE TIMESTAMP NOT NULL,
	CONSTRAINT ADDRESS_pk PRIMARY KEY (ADDRESS_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE CUSTOMER (
	CUSTOMER_ID serial NOT NULL,
	CUSTOMER_NAME varchar(60) NOT NULL,
	CUSTOMER_DOCUMENT varchar(15) NOT NULL UNIQUE,
	CUSTOMER_TYPE varchar(20) NOT NULL,
	CUSTOMER_CODE varchar(36) NOT NULL UNIQUE,
	CUSTOMER_SCORE varchar(20) NOT NULL,
	ADDRESS_ID integer NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	DAT_UPDATE TIMESTAMP NOT NULL,
	CUSTOMER_EMAIL varchar(70) NOT NULL UNIQUE,
	CUSTOMER_PASSWORD varchar(60) NOT NULL,
	CONSTRAINT CUSTOMER_pk PRIMARY KEY (CUSTOMER_ID)
) WITH (
  OIDS=FALSE
);



ALTER TABLE VEHICLE_DETAILS ADD CONSTRAINT VEHICLE_DETAILS_fk0 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE REGISTRY ADD CONSTRAINT REGISTRY_fk0 FOREIGN KEY (BATCH_ID) REFERENCES BATCH(BATCH_ID);

ALTER TABLE BATCH ADD CONSTRAINT BATCH_fk0 FOREIGN KEY (CUSTOMER_REQUESTER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE BATCH ADD CONSTRAINT BATCH_fk1 FOREIGN KEY (BATCH_DESTINY_ADDRESS) REFERENCES ADDRESS(ADDRESS_ID);


ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_fk0 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID);