CREATE TABLE DRIVER (
	DRIVER_ID serial NOT NULL,
	DRIVER_NAME varchar(60) NOT NULL,
	ADDRESS_ID integer NOT NULL,
	CAR_MODEL varchar(255) NOT NULL,
	CAR_DOCUMENT varchar(60) NOT NULL,
	DRIVER_DOCUMENT varchar(60) NOT NULL,
	DRIVER_SCORE FLOAT NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	DAT_UPDATE TIMESTAMP NOT NULL,
	CONSTRAINT DRIVER_pk PRIMARY KEY (DRIVER_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE REGISTRY (
	REGISTRY_ID serial NOT NULL,
	BATCH_ID integer NOT NULL,
	REGISTRY_DESCRIPTION varchar(255) NOT NULL,
	REGISTRY_REMAINING_TIME varchar(255) NOT NULL,
	REGISTRY_CREATION_DATE TIMESTAMP NOT NULL,
	CONSTRAINT REGISTRY_pk PRIMARY KEY (REGISTRY_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE REQUESTER (
	REQUESTER_ID serial NOT NULL,
	REQUESTER_NAME varchar(255) NOT NULL,
	REQUESTER_DOCUMENT varchar(20) NOT NULL unique,
	REQUESTER_USER_CODE varchar(36) NOT NULL unique,
	ADDRESS_ID integer NOT NULL,
	REQUESTER_SCORE VARCHAR(20) NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	DAT_UPDATE TIMESTAMP NOT NULL,
	CONSTRAINT REQUESTER_pk PRIMARY KEY (REQUESTER_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE BATCH (
	BATCH_ID serial NOT NULL,
	REQUESTER_ID integer NOT NULL,
	DRIVER_ID integer NOT NULL,
	BATCH_CODE varchar(255) NOT NULL UNIQUE,
	BATCH_UNLOCK_CODE varchar(10) NOT NULL,
	BATCH_ESTIMATED_TIME varchar(255) NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	CONSTRAINT BATCH_pk PRIMARY KEY (BATCH_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE ADDRESS (
	ADDRESS_ID serial NOT NULL,
	ADDRESS_STREET varchar(30) NOT NULL,
	ADDRESS_NUMBER integer NOT NULL,
	ADDRESS_BLOCK varchar(20) NOT NULL,
	ADDRESS_CITY varchar(30) NOT NULL,
	ADDRESS_CODE varchar(10) NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	DAT_UPDATE TIMESTAMP NOT NULL,
	CONSTRAINT ADDRESS_pk PRIMARY KEY (ADDRESS_ID)
) WITH (
  OIDS=FALSE
);

ALTER TABLE DRIVER ADD CONSTRAINT DRIVER_fk0 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID);

ALTER TABLE REGISTRY ADD CONSTRAINT REGISTRY_fk0 FOREIGN KEY (BATCH_ID) REFERENCES BATCH(BATCH_ID);

ALTER TABLE REQUESTER ADD CONSTRAINT REQUESTER_fk0 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID);

ALTER TABLE BATCH ADD CONSTRAINT BATCH_fk0 FOREIGN KEY (REQUESTER_ID) REFERENCES REQUESTER(REQUESTER_ID);
ALTER TABLE BATCH ADD CONSTRAINT BATCH_fk1 FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER(DRIVER_ID);