CREATE TABLE DRIVER (
	DRIVER_ID serial NOT NULL,
	DRIVER_NAME varchar(60) NOT NULL,
	ADDRESS_ID integer NOT NULL,
	CAR_MODEL varchar(255) NOT NULL,
	CAR_DOCUMENT varchar(60) NOT NULL,
	DRIVER_DOCUMENT varchar(60) NOT NULL,
	DRIVER_SCORE FLOAT NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	DAT_UPDATE TIMESTAMP NOT NULL,
	CONSTRAINT DRIVER_pk PRIMARY KEY (DRIVER_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE REGISTRY (
	REGISTRY_ID serial NOT NULL,
	BATCH_ID integer NOT NULL,
	REGISTRY_DESCRIPTION varchar(255) NOT NULL,
	REGISTRY_REMAINING_TIME varchar(255) NOT NULL,
	REGISTRY_CREATION_DATE DATETIME(255) NOT NULL,
	CONSTRAINT REGISTRY_pk PRIMARY KEY (REGISTRY_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE OWNER (
	OWNER_ID serial NOT NULL,
	OWNER_NAME varchar(255) NOT NULL,
	ADDRESS_ID varchar(255) NOT NULL,
	OWNER_SCORE FLOAT(255) NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	DAT_UPDATE TIMESTAMP NOT NULL,
	CONSTRAINT OWNER_pk PRIMARY KEY (OWNER_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE BATCH (
	BATCH_ID serial NOT NULL,
	BATCH_OWNER_ID integer NOT NULL,
	BATCH_USER_ID integer NOT NULL,
	BATCH_CODE varchar(255) NOT NULL UNIQUE,
	BATCH_ESTIMATED_TIME varchar(255) NOT NULL,
	BATCH_CREATION_DATE DATETIME(255) NOT NULL,
	CONSTRAINT BATCH_pk PRIMARY KEY (BATCH_ID)
) WITH (
  OIDS=FALSE
);



CREATE TABLE ADDRESS (
	ADDRESS_ID serial NOT NULL,
	ADDRESS_STREET varchar(255) NOT NULL,
	ADDRESS_NUMBER integer NOT NULL,
	ADDRESS_BLOCK varchar(255) NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	DAT_UPDATE TIMESTAMP NOT NULL,
	CONSTRAINT ADDRESS_pk PRIMARY KEY (ADDRESS_ID)
) WITH (
  OIDS=FALSE
);



ALTER TABLE DRIVER ADD CONSTRAINT DRIVER_fk0 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID);

ALTER TABLE REGISTRY ADD CONSTRAINT REGISTRY_fk0 FOREIGN KEY (BATCH_ID) REFERENCES BATCH(BATCH_ID);

ALTER TABLE OWNER ADD CONSTRAINT OWNER_fk0 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID);

ALTER TABLE BATCH ADD CONSTRAINT BATCH_fk0 FOREIGN KEY (BATCH_OWNER_ID) REFERENCES OWNER(OWNER_ID);
ALTER TABLE BATCH ADD CONSTRAINT BATCH_fk1 FOREIGN KEY (BATCH_USER_ID) REFERENCES DRIVER(DRIVER_ID);
